//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34209
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DefectTracking {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "12.0.0.0")]
    internal sealed partial class DefectTrackerSettings : global::System.Configuration.ApplicationSettingsBase {
        
        private static DefectTrackerSettings defaultInstance = ((DefectTrackerSettings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new DefectTrackerSettings())));
        
        public static DefectTrackerSettings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("http://bkrtfs01:8080/tfs/")]
        public string TFSuri {
            get {
                return ((string)(this["TFSuri"]));
            }
            set {
                this["TFSuri"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("BKR_FindingCollection")]
        public string TFScollection {
            get {
                return ((string)(this["TFScollection"]));
            }
            set {
                this["TFScollection"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("BKR Bevindingadministratiesysteem")]
        public string TFSproject {
            get {
                return ((string)(this["TFSproject"]));
            }
            set {
                this["TFSproject"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Finding")]
        public string TFSworkItemType {
            get {
                return ((string)(this["TFSworkItemType"]));
            }
            set {
                this["TFSworkItemType"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1 - Immediate")]
        public string BKR_Priority {
            get {
                return ((string)(this["BKR_Priority"]));
            }
            set {
                this["BKR_Priority"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Defect")]
        public string BKR_FindingType {
            get {
                return ((string)(this["BKR_FindingType"]));
            }
            set {
                this["BKR_FindingType"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("TFSProject")]
        public string ToscaTFSProject {
            get {
                return ((string)(this["ToscaTFSProject"]));
            }
            set {
                this["ToscaTFSProject"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("C:\\TOSCA_PROJECTS\\ToscaCommander\\Screenshots\\failedTestSteps")]
        public string ToscaScreenshotFolder {
            get {
                return ((string)(this["ToscaScreenshotFolder"]));
            }
            set {
                this["ToscaScreenshotFolder"] = value;
            }
        }
    }
}
